### ISSUE TITLE
Sustained notes get cut off when oversampling is > 1

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#10]
Oversampling set to 1 plays long sustained notes properly. However when set to x2,x4 or x8 the notes get cut off.

Example of SFZ that this is effecting (not limited to): https://github.com/sgossner/VSCO-2-CE/blob/SFZ/SViolinVib.sfz

**Comment by paulfd** [comment]
Thanks, I'll check it out! is it SSD or HDD, and are you using the debug build still?

Edit: I can reproduce it quite easily in the Debug build, and it also happens in release for more "stringent" requirements (e.g. oversampling x4 for 32k preloading size on my current laptop, and less so at 64k). I'd still like the debug build to work as well as it possibly could so I'll target to have it working with sane parameters. To solve it properly it may take a bit of time though so bear with me :)

Note for self:
- [X] Use a thread pool for background loading now that this operation is not disk-limited anymore
- [X] Reduce the debug verbosity
- [X] Increase the preload size possibilities

**Comment by AlexMitchellMus** [comment]
Debug build, and it's NVMe

**Comment by paulfd** [comment]
Building for release this does not appear for me unless I'm very aggressive on both oversampling (high ratios) and preload size. 

I chose in early development to not stream the samples (i.e. loading the full sample at once on request rather than loading samples chunk-by-chunk for quicker data access). This may have been unwise because i) if you oversample alot, the time it takes to load and oversampling a whole file at once can be quite daunting, and ii) the preload size does not only depend on the oversampling ratio, but also on the sample length which is a hidden parameter that may change between sfz instruments.

Considering both arguments and using it in practice, I am reconsidering my earlier decision and may just implement a form of streaming which adds complexity but has many advantages in practice.

**Comment by paulfd** [comment]
You can try a release build using
```
mkdir build-release && cd build-release
../scripts/release_gcc.sh
```

**Comment by AlexMitchellMus** [comment]
I will close this for now, but as you mentioned, deeper changes may have to happen to fix it completely.
