### ISSUE TITLE
Please implement hiprog/loprog

### ISSUE THREAD

**Issue by jlearman** [sfztools/sfizz#1047]
Please implement the `hiprog` and `loprog` opcodes, which are useful for those of us who use SFZ live and want to have more than 16 sfz instruments available, and/or to simplify programming our master keyboard to select an instrument using a patch button on the master keyboard.  Without this, I'll have to stick to Sforzando.

Ideally, this keyword should be scoped to the `<global>`, `<master>`, or `<group>` section in which it appears.

**Comment by jlearman** [comment]
I see at https://sfz.tools/sfizz/development/status/opcodes/?v=2 it says "not supported by design."  (It also says that for lochan/hichan.)  I'd be interested to hear why.

Seems to me it should be fairly simple to implement, factoring into the filter for a region.

For my purposes, hichan/lochan are superfluous.  I can manage MIDI channels just as easily in the live host or DAW, and frankly I find it better to do it there and let the player run in omni mode.  MIDI program is different.

Also, note that without these (both prog and chan) we can't use sfizz to play GM MIDI files, even if we have a GM MIDI sfz.  I don't do that but it might be a good use case for sfizz.

**Comment by paulfd** [comment]
> For my purposes, hichan/lochan are superfluous. I can manage MIDI channels just as easily in the live host or DAW, and frankly I find it better to do it there and let the player run in omni mode. MIDI program is different.

That's exactly the point actually. It's conceptually simple but kind of multiplies the size of some data structures by a factor of 16 which is wasteful in 99% of the situations SFZ is used for. In most cases as you said it just makes more sense to do channel dispatching at the host level. There's also really nothing stopping anyone from implementing for sfizz what the ARIA player is to sforzando.

`loprog`/`hiprog` is probably less costly because it seems like it's only an additional playing condition, but since I don't really know how program works and how people use them I decided not to support this at first.

**Comment by kinwie** [comment]
For efficiency, seems some developers are using internal converter trick.
My MIDI controller also has its own 'Extended MIDI CC' like we got in SFZ.
For example, the Mono Aftertouch or Channel Pressure message, is implemented as CC 144 in this device : 

![PC_cc145](https://user-images.githubusercontent.com/65444898/144147968-ec79e0f4-c891-4038-90ed-15ccc2b1f5e3.png)

As we know we have Mono Aftertouch as CC 129 in SFZ, which is the same concept.

And it also treated Program Change message as CC 145.
So which I guess the trick is, use an alias as a CC number, then transmitted it as message that compatible for Program Change.
That probably can save quite amount of unnecessay CPU resources maybe?

In reverse process for sfz, we receive the Program Change message and read it as CC message then apply that to a new CC message (said CC 170 or CC 5000). And then implement locc5000 - hicc5000 as alias to  `loprog` and `hiprog`
I wonder if sforzando also use this kind of trick...

**Comment by jlearman** [comment]
Thanks Kinwie, though I'm not sure I follow it all!

Paul, here's some background on `prog` from an old guy.  It dates back to hardware keyboards.  A keyboard would have a row of buttons for choosing the sound (program).  And usually a "bank change" method so that if there are only 8 buttons you can access more than 8 programs.  This appeared with the first digital keyboards, prior to MIDI.  When MIDI appeared, they just included this behavior, so that if I choose program 10 on my master keyboard, and if my slave keyboard was configured to receive prog change messages, that would also choose program 10 on the slave.  Therefore, pushing one button on the master keyboard could affect the sound for that keyboard and any slaves.  VERY helpful for live use, to push one button rather than one on each keyboard, for a given song or passage.

Here's how I use it today.  I currently have one keyboard, a Yamaha CP4.  I use a number of its internal sounds, plus I have it connected to a Windows laptop (that folds back on itself so it sits on my music rest with keyboard hidden.)  The CP4 has 16 patch keys that are programmable, so that whenever I select one it selects any internal sounds (and key split/layer) and also selects the output for MIDI for that patch, which can be different for different zones.  For each zone (I usually need only one), I can program the MIDI channel and the MIDI program number.

On the laptop, for most MIDI channels, I have one plugin setup to respond to that channel.  These are my "bread-and-butter" sounds.  Of these, 3 aren't usable for unimportant reasons, and 3 are assigned to Hammond, so I have 10 left over.  But I want more than 10 sounds.  So, I put all the "extra" sounds (ones that I won't layer with each other) in one big SFZ and use the MIDI prog feature to select the sound.  Personally I always have hiprog and loprog set to the same number.  Using ranges allows clever tricks for layering, but I use "clever" as a pejorative: like write-only code IYKWIM.

**Comment by kinwie** [comment]
I was aware to what written at sfizz page about `loprog/hiprog` that "Not supported by design" note. I was making my own guess that it might be because of so many MIDI features was stripped-out from VST3 format, which might caused MIDI Program Change can't be supported in sfizz. Of course I might be totally wrong as it just a wild random guess.

So I just gave some examples, using trick like how it seems done on my MIDI controller. Treated MIDI ProgChange like a regular MIDI CC and implement a way to read it as loprog/hiprog value.

My Midi controller has a dedicated ProgChange buttons along with the LSB/MSB (Bank select) buttons to do the GM style presets selection. But it's a two-step way pressing. So you press the Up/Down (+/-) ProgChange button and then Enter to confirm the selection. This way, the Bank Select message also need to be matched (Bank number and Perc/Melodic patch number). Sounds complicated hahh! Just like the old GM keyboard way.

But I can assign a new CC to a rotary knob, so it can control the ProgChange with just one-time turn of that knob and with no LSB/MSB affected. It just change the Program number regardless the Bank selection. It's a cool additional hack, imho.

So, from that above MIDI CC list I posted previously, I assign MIDI CC 145 (which is the ProgChange's extended CC number in my keyboard) to a knob and it transmitted that CC message as ProgChange message but without sending Bank select message to be received by sforzando.
_*I tested it with a SFZ GM I made years ago, the Fluid R3 GM SFZ bank_

Never mind... I just show-off :p

**Comment by paulfd** [comment]
So #1058 has loprog/hiprog, but apparently midi program changes and VST3 do not mix well. In LV2 it works fine. I don't know which one you use @jlearman .

**Comment by jlearman** [comment]
Thanks!  I tried VST3.  I haven't tried any LV2 plugins yet, but maybe now is the time.

Just curious, is this a flaw in VST3 definition, or just an issue with Sfizz implementation?

In any case I am satisfied with this resolution.

**Comment by paulfd** [comment]
Yes VST3 basically removes alot of the MIDI "Legacy" things. It's hard to do a MIDI only plugin in VST3 afaik...
