### ISSUE TITLE
Setup GitHub sponsors

### ISSUE THREAD

**Issue by kmturley** [sfztools/sfizz#1101]
Sfizz has been developed and maintained by two developers:
https://github.com/sfztools/sfizz/graphs/contributors

You both have limited time/resources, and are not able to keep pace with feature suggestions and issues coming from the community:
https://github.com/sfztools/sfizz/issues

In order to solve this you need more code contributors, but also a way that regular users can support the project.

GitHub sponsors allows us to support financially, which could be used to pay developers to build out new features.
https://github.com/sponsors

If you enable the feature, you can set funding milestones. We could encourage community members to sponsor the project. By hitting those milestones then a feature would be released e.g.

- $100 - Bug fixes and performance updates
- $1000 - Configurable user interface
- etc

Thanks!

**Comment by paulfd** [comment]
Hey!

Thanks for proposing. Actually we set up an open collective a while ago. One of the core reason for this choice is that I do not wish to receive donations in my own name, and this means that "sfizz" or "sfztools" would need to have some form of legal existence (i.e. probably being setup as a non-profit in my country at least) and properly declare donation incomes, etc. Open collectives allow to create umbrella organizations that handle the legal and tax stuff so you don't have to, as well as a transparent feedback for the use of donations to the donors, so it seemed appropriate to me. When I checked a couple years ago this was the only satisfying option in Github sponsoring to me, maybe there are new ones now; which one would you propose?

I also do not want to get anyone hopes up too much (if they ever would) since for many good reasons I can't promote sfizz to anything more than a hobby project of mine for now. As such do not plan to use the donation funds for anything other than fees related to e.g. websites or (insert commercial OS) developer racket. @jpcima might have different views, we might revisit financing some of his work through the open collective anytime. Other interested people can also DM me on discord or by email. The bounties idea could be interesting too !

**Comment by kmturley** [comment]
Oh I see it at: https://opencollective.com/sfztools I have setup recurring contributions to support your work!
Thanks for all the great work!
