### ISSUE TITLE
API: Mono rendering

### ISSUE THREAD

**Issue by Ravbug** [sfztools/sfizz#1131]
The documentation for [Sfizz::renderBlock](https://sfz.tools/sfizz/api/classsfz_1_1_sfizz#renderBlock) states that the output parameter is expecting stereo buffers. 

Is it possible to render out as mono instead? I am trying to use Sfizz in a game engine, where the audio will be spatialized by the 3D sound system, so I need a mono output from Sfizz.

**Comment by paulfd** [comment]
@Ravbug Sorry for the late reply! You can still render to a stereo buffer (which a relatively small memory spaces by modern standards) and then use the left or right channel or sum their output to get a "center" channel. It may change in the future because there are some cases where mono outputs would make sense but don't count on it too soon.
