### ISSUE TITLE
How to build project to generate static library that can be linked to C++ or Rust project?

### ISSUE THREAD

**Issue by SuperiorArri** [sfztools/sfizz#1184]
Hello,

I am trying to build sfizz to static library. First I tried to build it and link it to a Rust executable, but I am getting some undefined reference errors. So I made a simple C++ project with cmake to reproduce the same error with C++.

So first I made a folder containing recursive clone of this repo. I build the project with cmake (I am including CMakeCache.txt).
[CMakeCache.txt](https://github.com/sfztools/sfizz/files/12388835/CMakeCache.txt)
Then I added main.cpp and CMakeLists.txt: 
[sfizz_static_link_test.zip](https://github.com/sfztools/sfizz/files/12388845/sfizz_static_link_test.zip)

When I try to compile my code I get this log:
[log.txt](https://github.com/sfztools/sfizz/files/12388852/log.txt)

I also tried linking other .a libraries generated from the first build but I get even more errors.

How can I build and link the static libs properly?

Thank you for your help.

EDIT:
I also tried to link dynamic lib and it works, but I would really prefer to use static linking in this case.

**Comment by paulfd** [comment]
Hello. The particular symbols in your log are located in `libsfizz_internal`, which contains the sfizz engine C++ part. These symbols are _not_ advertised in the "front-facing" C static library `libsfizz.a` in your setup. If you wish to follow this path, you need all of these static libraries you commented, and maybe more since I don't see many of the static dependencies in your list. By itself, a static `.a` library is only a collection of objects files (a stands for "archive" afaik) that did not entirely go through the linking process. A CMake project will create a static library for each of the `add_library` call, and you're encourage to create many to make your compilation process cleaner and more modular. There are some ways to bundle all the static libraries into one out of the CMake compilation, e.g. https://gist.github.com/cristianadam/ef920342939a89fae3e8a85ca9459b49 but I never tried.

If I understand correctly what you're trying to achieve you might have better luck starting from the makefile `generic.mk` in the root of the repo. I'm not on a linux machine atm so I can't test, but I believe it would output a static library closer in form to what you expect. It lists all necessary object files to compile the sfizz engine, or at least it should, and puts them all in a single archive.

**Comment by Arri0** [comment]
> Hello. The particular symbols in your log are located in `libsfizz_internal`, which contains the sfizz engine C++ part. These symbols are _not_ advertised in the "front-facing" C static library `libsfizz.a` in your setup. If you wish to follow this path, you need all of these static libraries you commented, and maybe more since I don't see many of the static dependencies in your list. By itself, a static `.a` library is only a collection of objects files (a stands for "archive" afaik) that did not entirely go through the linking process. A CMake project will create a static library for each of the `add_library` call, and you're encourage to create many to make your compilation process cleaner and more modular. There are some ways to bundle all the static libraries into one out of the CMake compilation, e.g. https://gist.github.com/cristianadam/ef920342939a89fae3e8a85ca9459b49 but I never tried.
> 
> If I understand correctly what you're trying to achieve you might have better luck starting from the makefile `generic.mk` in the root of the repo. I'm not on a linux machine atm so I can't test, but I believe it would output a static library closer in form to what you expect. It lists all necessary object files to compile the sfizz engine, or at least it should, and puts them all in a single archive.

Cool, the CMake budle function from https://gist.github.com/cristianadam/ef920342939a89fae3e8a85ca9459b49 worked! Than you very much.

**Comment by SuperiorArri** [comment]
> Hello. The particular symbols in your log are located in `libsfizz_internal`, which contains the sfizz engine C++ part. These symbols are _not_ advertised in the "front-facing" C static library `libsfizz.a` in your setup. If you wish to follow this path, you need all of these static libraries you commented, and maybe more since I don't see many of the static dependencies in your list. By itself, a static `.a` library is only a collection of objects files (a stands for "archive" afaik) that did not entirely go through the linking process. A CMake project will create a static library for each of the `add_library` call, and you're encourage to create many to make your compilation process cleaner and more modular. There are some ways to bundle all the static libraries into one out of the CMake compilation, e.g. https://gist.github.com/cristianadam/ef920342939a89fae3e8a85ca9459b49 but I never tried.
> 
> If I understand correctly what you're trying to achieve you might have better luck starting from the makefile `generic.mk` in the root of the repo. I'm not on a linux machine atm so I can't test, but I believe it would output a static library closer in form to what you expect. It lists all necessary object files to compile the sfizz engine, or at least it should, and puts them all in a single archive.

Cool, the CMake bundle function from https://gist.github.com/cristianadam/ef920342939a89fae3e8a85ca9459b49 worked! 

Thank you very much!
