### ISSUE TITLE
Change the parameters in the LV2 plugin

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#157]
I'm not super fan of the current parameters in LV2, for many reasons. For one, these are not _lightweight_ parameters and actually cause the whole plugin to change its state, reload files, etc. Some of them could also live within sfz files as either known opcodes or `sfizz_` or `hint_` opcodes.

Here are possible approaches we could explore:
- The polyphony parameter could be set to default higher (say 128 and 256) and be overriden in sfz files by the `polyphony` opcode when present in a `global` header. Right now the opcode is more meant for `group` header where it's supposed to control group polyphony.
- The oversampling parameter, while working, will be overridden/enhanced by further work on the resampling hopefully. It could be also control by an opcode (say `hint_oversampling`). The sfz v2 book also mentions a quality opcode for the resampler.
- The preload size could be heuristically set through testing depending on the sfz library (is it flac, ogg, wav...) and the hard drive speed of the user. In particular, there is already a logging facility for load times of the files. This would be pretty great for usability: the library would choose and possibly adapt its own preload size automatically.
- Overall, I wonder if we could also allow some tweaking of the defaults and heuristics using e.g. a single LV2 string Atom type and a patch property. For example, you could override the preloading or set the oversampling by filling `oversampling=4 preload_size=64k` or something. This is not super friendly, but it's not meant to be because parameters in there are supposed to be somewhat expensive and experimental.

This is more for discussion for now! 🙂

**Comment by paulfd** [comment]
Note that jalv show string parameters in the generic UI but not Ardour.

**Comment by AlexMitchellMus** [comment]
I agree that **Preload**, **Oversampling** & **Polyphony** can be confusing, and provide too much information to end users.

However I am between two minds with Polyphony setting.
Mainly because almost every soft-synth (and sampler) has this setting available to the user.

From a musicians perspective, while Polyphony is about resource management, it's also a value that needs to be known and editable, as it can drastically change, and change _with_ the playing style of the user. However as polyphony is so tied to instrument behaviour in SFZ, I don't really know how one can easily change this setting- apart from instruments that don't use polyphony management at all (as behaviour).

Preload size is a perfect opportunity for the system to self tune. It has no effect on performance (apart from under-runs of buffer). Depending on ram pressure it should auto-tune. (Maybe even dynamically?)

## One slider to rule them all
Alternatively there could be a **System Performance** slider, with low-mid-high sort of concept.

Such a slider would control Preload, Polyphony & Oversampling. 

In the SFZ book, the opcode: `sample_quality` sets the method for resampling, as opposed to its oversampling. (It is discussed that 1=Linear, 2=High, 3->10 is various sinc resampling algorithms).

Anything that effects the sound of a SFZ instrument, should be present in the SFZ script.

I'm not sure if for example offline-rendering should be highest oversampling quality, as it really depends on how it effects the overall instrument sound. Remembering that lower quality sampling methods can contribute to the sound of an instrument.

I can only imagine linear being used as an effect, thus if `sample_quality=0` (low quality for effect) then that would override high quality offline-rendering.

Thus a main **System Performance** slider, would allow sfizz to tune the SFZ script, based on what is already present in the script, but also allow the user to manually let sfizz know how much resources it is allowed to use.
