### ISSUE TITLE
Can not reload changed SFZ file in LV2 plugin

### ISSUE THREAD

**Issue by SpotlightKid** [sfztools/sfizz#17]
When the host sends an `atom:Path` msg for the `http://sfztools.github.io/sfizz:sfzfile` param with the same SFZ file path as the one already loaded, sfizz [skips file loading](https://github.com/sfztools/sfizz/blob/62b64f7eff88fb69502708d9ffc56d9d8dcd74ea/lv2/sfizz.c#L474).

This prevents the user from reloading a SFZ file, which has changed (i.e. the SFZ file was edited after loading). The user needs to remove and re-add the plugin instead, which is cumbersome.

IMO, the sfizz plugin should reload the SFZ file unconditionally or store a modification time and/or hash for the file contents and only skip loading if both of these match.

**Comment by paulfd** [comment]
Yes, just today I was thinking about having a live reload so I'll revisit all of this, thanks for the report!

**Comment by paulfd** [comment]
Ok from c0f7b4f8b3ee388a6c9ec235655cc4c3fe0a3142 you can force reload a file, and from 8806ec221550d93a56345d2e87d0167f9b0b1b52 it actually checks the file modification date to reload it if necessary.

At first I decided that this would be better to have it on the LV2 side rather than launching yet another thread on the C++ backend side, but the issue with this solution is that it only checks the root sfz file and not possibly #included files. As I assume that people developing libraries would like to have the file reloading on any file changes, I wonder if something a bit hybrid would make sense: have a `bool sfzFileWasModified(...)` to check for changes of all the included files, but have the LV2 plugin trigger the reloading on its own time. A good side effect of this is that using `std::filesystem` the file modification time check would be cross-platform.

I will let this open to track eventual opinions on this for now.

**Comment by redtide** [comment]
I don't see why we need a filesystem watcher for modification?
Can't we just collect all file's date time when loading a sfz file initially and on a reload request read them again and compare with previous stored ones?

**Comment by SpotlightKid** [comment]
Checking the whole tree of included files opens a whole can of worms, though. A change in an SFZ file might also change the dependency of included files. I'm not sure if it is worth the effort to detect, if and when any of the main and the included SFZ files need to be reloaded. Maybe a simple, unconditional full reload when requested is much easier, at least for now.

**Comment by paulfd** [comment]
Okay I tried something actually simpler in f02f96cad59a1357a46d4157da360ecd9c7e15a9 (which in turns allow the mac version to build :sweat_smile:).

@redtide sforzando actually does this and I guess people developing libraries kinda like to see live the changes they made..
@SpotlightKid you're right that there may be some corner cases that I did not see here... for now, if the timestamp of any included file is more than the timestamp of the latest file at the time of the loading, everything gets wiped and reloaded -- as would a full reload. Since there's not partial reload you should be able to avoid some can of worms.

In any case, it's now quite easy to disable all over and the full reload can be triggered by a new `atom:path` in any case. If you encounter any issue with this behavior let me know and I'll gladly reevaluate :)

**Comment by redtide** [comment]
@SpotlightKid A full reload for some instruments can take time (not much nowadays, but quite annoying sometimes). I don't see a problem by storing some array/map of filenames/date times on load and compare with previous saved ones.
@paulfd I planned to do it in my UI (and I did) but I don't see why do this in the library, I feel it as unnecessary.

**Comment by paulfd** [comment]
The library does not do anything, but it advertises a method to check the reload time: `bool sfz::Synth::shouldReloadFile()`. It's up to the frontend (e.g. your UI or the LV2 plugin) to actually trigger the reload, in particular because it needs to be done on a background thread.

**Comment by redtide** [comment]
I was referring to 8806ec2, at least I got it as "do a check every x times automatically", and later moving it to the library in f02f96c. I didn't check the code so IDK what it does, so if it doesn't it's OK to me, just got it wrong.

**Comment by SpotlightKid** [comment]
> A full reload for some instruments can take time

That should be at least somewhat mitigated by the fact that sfizz, AFAICT, does on-demand loading of samples and it only loads a portion of (all?) samples at init.

@paulfd Correct me, if I'm wrong there.

**Comment by paulfd** [comment]
No that's correct, but it can still take some seconds to load a file depending on the number of samples.
