### ISSUE TITLE
Improve the note stealing

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#187]
Use the power history to kill the quietest note if below some threshold.

**Comment by paulfd** [comment]
> @Paul Fd a major heuristic would be to increase the kill probability of repeated notes (the same key repeated) as opposed to unique notes. As repeated notes are not going to be adding to the harmonic structure, as that tone is already present. No point killing off c2, when c3 is being played constantly. Look at the Chopin spectrum! In that example there is a repeated chord in the middle that is using up all the poly for no good reason.

![](https://cdn.discordapp.com/attachments/620871552627376148/708251019535974480/Screenshot_2020-05-08-19-06-04-793_com.discord.png)

**Comment by paulfd** [comment]
Other possible improvements and things to try:

- [x] Implement a "real" fast release and use this instead of the ad-hoc ramping done in the render block.
- [x] Have a "dying" voice pool that are fast-released, which could allow for multi-block decay (or block-size independent decay)
- [x] Maintain a state of voices started on a given number as high candidates for stealing. In general, maybe move to a score-based approach.
- [x] Consider honoring [note_selfmask](https://sfzformat.com/opcodes/note_selfmask) even outside of the note polyphony context

**Comment by AlexMitchellMus** [comment]
Some background on the spectrogram image:

* sfizz #214 
* Chopin Piano concerto No. 1 in e minor, Op. 11 1. Allegro http://www.kunstderfuge.com/chopin.htm
* top 8 note polyphony
* bottom 256 note polyphony

SFZ file:
```
<region>
sample=*sine
ampeg_attack=0.1
ampeg_decay=0.1
ampeg_sustain=50
ampeg_release=0.1
```

**Comment by FrnchFrgg** [comment]
Some remark: the recent change of default maximum voices to 256 means that by default sfizz uses much more DSP, especially in SFZ instruments like drums that do not cater specifically for polyphony or buildup reduction. Same for instruments with long decay/sustain. At low periods/latencies that can make sfizz unusable "by default".
Somebody explicitely increasing the polyphony can expect sfizz to consume more, and know which setting did that. Somebody just instancing an SFZ and getting xruns might just conclude that sfizz is broken and move on.

Especially with better voice stealing, using a default of 256 is not really needed.

**Comment by FrnchFrgg** [comment]
Also, score based stealing is probably the way, because you shouldn't prioritize "same note" stealing over "other note stealing" for arbitrary volumes. With roughly similar volumes of all currently playing voices, stealing an old voice of the just played note can be a good idea, but if every "old voices of the current note" still have strong volume compared to other notes voices that's not so. The question is where to draw the line.

Also, beware that stealing a currently playing "old voice" for the current note might sound very bad if the new note played is very low velocity (imagine a very light ride pattern played just after two or three bigger hits, and the ringing stops abruptly).

The example provided here is not impacted as much by this problem because a piano is not `one_shot`. Maybe you want different tuning of voice stealing parameters depending on whether one_shot is on or off (or maybe not because sustain essentially makes piano behave as if `one_shot` is used, barring loops).

**Comment by AlexMitchellMus** [comment]
Should not `polyphony` opcode be used in drums?

**Comment by FrnchFrgg** [comment]
@alcomposer I think that's orthogonal. No matter what polyphony setting is used, if voice stealing mutes some still loud ringing of the current note instead of stealing near-silent tail of another note, that's bad.

Of course I am describing the kind of voice stealing that is needed when reaching the maximum configured voice count, which is a performance parameter, and depends on the current usage (live with very low latency, offline, etc.), not on the instrument itself (so should *not* be increased by an override in the SFZ file, as was suggested in another issue).

When stealing voices due to `polyphony` opcodes, this is similar, but if the opcodes only allow to steal from the same note (because it is the only one in its group), then sfizz would of course do so (same as if the only samples playing currently are a single note and you reach the global maximum).

**Comment by paulfd** [comment]
There is an upcoming stealing behavior runtime selection through `hint_` opcodes. This setup also makes it easier to implement different type of stealing and possibly to experiment. I'll close this for now as we're basically matching ARIA's behavior by default, with the possibility of finer control on the stealing.
