### ISSUE TITLE
v0.3.2 cmake error

### ISSUE THREAD

**Issue by Gooberpatrol66** [sfztools/sfizz#220]
[CMakeOutput.log](https://github.com/sfztools/sfizz/files/4602555/CMakeOutput.log)
[CMakeError.log](https://github.com/sfztools/sfizz/files/4602556/CMakeError.log)

**Comment by jpcima** [comment]
Hello, can you explain what is the problem exactly?

You error logs just shows some failing feature checks, which are expected and normal.

**Comment by Gooberpatrol66** [comment]
It fails without generating a makefile.

**Comment by redtide** [comment]
Can you provide some steps you did to build it so we can try to reproduce the issue?
E.g.: was it a git clone or our package?
If it was a git clone was the submodules checked out as well with `git submodule update --init --recursive` command? GitHub also offers zip/tar.gz packages automatically that don't contains the required submodule dependencies. Which commands gave you to configure/build the project?

**Comment by Gooberpatrol66** [comment]
Downloaded https://github.com/sfztools/sfizz/archive/0.3.2.tar.gz
cd sfizz*
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..

**Comment by redtide** [comment]
So unfortunately you got one of the GitHub automatically created archive assets, which doesn't contains git submodules of required dependencies, we need to find a way either remove them or maybe warn to not use them since they are incomplete.
The source code you are searching for is <https://github.com/sfztools/sfizz/releases/download/0.3.2/sfizz-0.3.2-src.tar.gz> instead.

**Comment by Gooberpatrol66** [comment]
Ah, I see. Thanks.
