### ISSUE TITLE
Request: make download optional.

### ISSUE THREAD

**Issue by magnetophon** [sfztools/sfizz#24]
I'm packaging sfizz for NixOS, and since nix doesn't condone downloads during the build, the [FetchContent_Populate](https://github.com/sfztools/sfizz/blob/develop/lv2/CMakeLists.txt#L26) commands won't work without [hacky patching](https://github.com/mujx/nheko/issues/271#issuecomment-376198319).

Would you consider making the downloads optional?
Why didn't you choose to include them as dependencies?

**Comment by paulfd** [comment]
Hi! I've actually been bitten back by the FetchContent since it blocked me from re-configuring without Internet access. We will probably reevaluate this.

What do you mean by dependencies? The external content are not shared libraries, they are to be statically linked into the binaries. I have found that there is nothing satisfying for proper "static" cross-platform library management for C++:

1. CMake ExternalProject and FetchContent download stuff at build and configure time respectively, which apparently some people hate with passion and which are annoying to deal with when no internet connection is available.
2. Git submodules look like a good solution but are brittle and will sometimes break for no apparent reason. They also are not always well handled by most of the VCS tools in common development environments.
3. There are some helper tools like `Hunter` or `vcpkg` but they add external dependencies and requirements for builds. You also add complexity when you want to integrate a library that is not a part of the standard list. `vcpkg` also has some issues if you have things like in Abseil where `absl::string_view` gets aliased to `std::string_view` in C++17 but not before: `vcpkg` will pre-build the type alias as if you'd build everything else against C++17 and so your build will break if you force C++14 compatibility.
4. Downloading whole repositories in your own can work but seems a bit dirty; it's also a straightforward way to miss updates and just let the thing rot inside your repository.

After spending hours fighting these we might just go for solution 4---it's already like this for a number of "smaller" libraries like Catch. It's not pretty but it has the good taste of being less annoying. I do have to admit that I'm not really used to working in this type of environment, so I may have missed something entirely. I you have a better solution I am all ears :slightly_smiling_face:

**Comment by jpcima** [comment]
Can you elaborate about problems regarding git submodules ?
These are good in my experience.

>After spending hours fighting these we might just go for solution 4---

It's not such a terrible choice to go by this method, in honesty.
Lv2 is header-only, and it needs update only if you want latest additions.
DPF, for instance, includes the whole lv2 header set.

**Comment by redtide** [comment]
I think the solution is by using pkgconfig for the "big" external ones (dynamically linked), and using point 4 to embed the small ones. On Arch linux at least it's simple, LV2 is added as make dependency, used only for build, but at this level it would be easier, as jpcima say, to embed a stable version and update it time to time like others for the main library. There is also a problem to how to handle static builds (Windows mainly), but I suppose there vcpkg solve the problem. We miss some MinGW builds.

**Comment by paulfd** [comment]
@magnetophon You can try the develop branch, we removed the FetchContent so that for the basic build you only need the dependencies and the abseil submodule. Tell me if that works out for you.

@jpcima I had multiple times where the submodule became "dirty", or when some ghost commit reference was pushed to the repository which blocked further clones. This has been somewhat alleviated using a specific branch that stays stable. I also mostly use the command line now and I think many problems were due to my handling submodules incorrectly within the git tools I used. It left me with this brittle image...

**Comment by magnetophon** [comment]
@paulfd Thanks a lot,it compiles and runs now!

I haven't been able to get a sound yet; I optimistically loaded a .gig file and got the most spectacular crash I've seen in a long time!

First a period of line-noise into the terminal that I started jalv.gtk from.
PC unresponsive except for mouse-movement.
Then the terminal displayed stripes.
After a while I gave up an pressed the power button.

Would you prefer I close this issue and open a new one for the crash?

Lemme try a .sfz now...  :)

**Comment by magnetophon** [comment]
Update: .sfz works.
Thanks!
