### ISSUE TITLE
Make it possible to start sfizz without loading a sfz file

### ISSUE THREAD

**Issue by grammoboy2** [sfztools/sfizz#254]
$ sfizz_jack 
You need to specify an SFZ file to load.

This should be possible from the GUI I think, which would give a better user experience and it would be needed for potential NSM support.
 
I'm also not sure why the executive name isn't just sfizz. I know that these kind of unexpected names can make people confused when using the non-session-manager(NSM).

**Comment by paulfd** [comment]
Hi,

I don't remember if I mentioned this but we have no GUI for this app (yet?) so that's why we need to pass in the sfz file in the call. The name is not great, but it has the upside of not letting anyone think that this works with alsa or pulseaudio :slightly_smiling_face: When it's a bit more than just a test app I think we can rename it.

At the moment, your best JACK experience is probably going to come from jalv!

**Comment by jpcima** [comment]
When we have finished the generic editor, it can be attached to the jack standalone as well.
It's not finished currently but it's in good progress.

**Comment by redtide** [comment]
Not sure but it might be good to have some "headless" version of the client, so maybe we could have a "sfizz" GUI keeping the current one as is?

**Comment by grammoboy2** [comment]
I do agree that a headless version is a 'must have'. I'm in general pretty content with the linuxsampler (headless) and Fantasia (generating lscp files) workflow, apart from the fact that it lacks SFZ developments. If the GUI has NSM support, it would be nice to have.

**Comment by paulfd** [comment]
This is specifically doable now, I'll track the NSM part in the other issue.
