### ISSUE TITLE
Sine default instrument inconveniences

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#296]
When a music project was designed for an older sfizz, and it contains unused instances without a SFZ file assigned, they are now going to play as sine wave. This has been reported as an inconvenience.

In this case, let's not make the parameter empty value equivalent of the default patch, but use something else.

**Comment by paulfd** [comment]
I feel like this goes against the idea of a default patch, doesn't it?

**Comment by jpcima** [comment]
Possibly, I don't have currently a better idea in mind.

**Comment by paulfd** [comment]
OK so I tried to give a name to the default sine instead of `""`, and uncovered some strange behavior. Right now on develop, we save the state which gets recorded as follows:
```ttl
	a pset:Preset ;
	lv2:appliesTo <http://sfztools.github.io/sfizz> ;
	state:state [
		<http://sfztools.github.io/sfizz:sfzfile> <> ;
		<http://sfztools.github.io/sfizz:tuningfile> <> ;
		<http://sfztools.github.io/sfizz:numvoices> "64"^^xsd:int ;
		<http://sfztools.github.io/sfizz:preload_size> "8192"^^xsd:int ;
		<http://sfztools.github.io/sfizz:oversampling> "1"^^xsd:int
	] .
```
Fine, empty string and everything. The issue is that upon reloading, Ardour passes the path `/home/paul/Ardour Sessions/Empty/plugins/226/state1/state.ttl` instead of an empty string to restore, which then goes through this function:
```c++
static bool
sfizz_lv2_load_file(LV2_Handle instance, const char *file_path)
{
    sfizz_plugin_t *self = (sfizz_plugin_t *)instance;

    if (file_path[0] == '\0')
    {
        if (!sfizz_load_string(self->synth, "default.sfz", default_sfz_text))
            return false;
    }
    else
    {
        if (!sfizz_load_file(self->synth, file_path))
            return false;
    }

    sfizz_lv2_update_file_info(self, file_path);
    return true;
}
```
The branch taken is the second one, i.e. `if (!sfizz_load_file(self->synth, file_path))` and it rightly fails to load, leading to an early return. The value for the file path is never updated, and it stays at the default `""`. 1 second later, the modification checker runs, and tries to "reload" the current file, thereby calling `sfizz_lv2_load_file(self, self->sfz_file_path)` where `self->sfz_file_path` is empty, thus reloading the default sine instrument.

From what I see I think that it's actually lilv replacing what it sees as relative paths by "absolute" versions. In the process I tried, the path was stored as `SFIZZ_DEFAULT_PATCH`. Upon reloading the state, I get
```
Loading /home/paul/Ardour Sessions/Empty/plugins/226/state2/SFIZZ_DEFAULT_PATCH
Parse error in "SFIZZ_DEFAULT_PATCH" at line 1: Cannot open file for reading: /home/paul/Ardour Sessions/Empty/plugins/226/state2/SFIZZ_DEFAULT_PATCH
```

While a potentially interesting idea, I feel like this will require either ugly hacks or changes upstream in lilv to support the behavior we intend. I am half convinced to just withdraw the feature. An alternative maybe is to use http://lv2plug.in/ns/ext/state#makePath to store a copy of the "default" in the state directory for empty files?

**Comment by paulfd** [comment]
Even makePath is a bit messy. Ardour has a makePath feature at instantiation (https://github.com/Ardour/ardour/blob/a3e30f72f048e615166af4bdf4e04eab69882237/libs/ardour/lv2_plugin.cc#L1407) but it seems to except in my version with a string error. Lilv handles the makePath during saving and it works fine, but this does not solve our current predicament since old versions saved and restored will still sound the sine after the saving step.

The "best" way forward would maybe be to understand what's wrong and debug Ardour. I'll see if I can build a dev version :D

I'm pushing my tentative in #302 for now.

**Comment by jpcima** [comment]
It's a lot of complexity behind this path handling mechanism.
Let's revert this for now?

**Comment by paulfd** [comment]
I agree. I am still a bit concerned by the fact that lilv sends back the `state.ttl` file on restore, which generates a parsing error when restoring empty paths. Do we hard-encode a check for this?

**Comment by jpcima** [comment]
Isn't this a problem of Ardour, not ours? I can experience it here also.

Also I study the implementation of `state:mapPath`, as mandated by LV2 spec.
It creates a symlink chain like this.
```
a6-state-paths/plugins/227/state2/saw.sfz -> ../../../externals/saw.sfz
a6-state-paths/externals/saw.sfz -> /home/jpc/desktop/saw.sfz
```

Wouldn't it resolve the issue of sidecar files to resolve the symlink chain in the sfizz library ?
