### ISSUE TITLE
The resampler

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#33]
I posted a simple convolution-based resampler.
https://github.com/jpcima/simple-resampler

It has an example in the repo, to try it on sound files.

It has these properties:
- it has a latency/quality compromise controllable at compile-time, by setting template parameters
- the inner loop can be written as SIMD code, and also unrollable by compiler since it's a known length
- it's a Lanczos window, but could be edited for something else
  https://en.wikipedia.org/wiki/Lanczos_resampling
- currently it uses "functional-style" interface and inlines into the caller
- ~limited to single channel, it's a thing to improve later~

**Comment by jpcima** [comment]
Note: I found this document
http://ldesoras.free.fr/doc/articles/resampler-en.pdf

As I found, the document describes a solution in section 3 which is very much like that is implemented, except some differences:

- linear interpolation of the convolution kernel, instead of lookup into a large table
>The continuous interpolator’s side-lobes are only caused by the impulse
windowing whereas origin of the main side-lobes of the discrete interpolators is the phase bit
reduction. In these conditions, we have to increase M to unacceptably high values to get a
decent SNR. That is why it is necessary to interpolate correctly the functions Gd[k].

- oversampling x2 for aliasing headroom
cf. top figure page 11

It's expectable that these additions may fix the quality problems so far, although oversampling 2x will be a bit more expensive in computation. At present, there is lot of foldover in high frequencies, but oversampling must be able to help fix that.

**Comment by paulfd** [comment]
Heh I use one of de Soras' IIR oversampler internally. At first, my idea was that you could have the cake and eat it too by oversampling as much as possible on the background thread for samples, and using linear interpolation on the RT thread since nothing will beat that in terms of live speed. The downside of this approach is that you need to oversample the preloaded data, which double the memory requirements on each oversampling step.

From this point of view, doing a reasonable oversampling on the background thread and a slightly better interpolation on the live thread is probably a good compromise. For freewheeling rendering, the algorithm could also be switched to better polynomials/higher oversampling.

Along the same lines, I still have this vague idea I promised you, whenever I have time I'll write it down and test it to see if it's possibly interesting or just useless 🙂 I can be adapted to any of these approaches I think.

**Comment by jpcima** [comment]
a 4-point interpolation polynomial, implemented in scalar and SSE.
cf. section 1.3 http://yehar.com/blog/wp-content/uploads/2009/08/deip.pdf


```
#include <xmmintrin.h>

template <class R>
R Hermite3rdOrder(R x)
{
    x = std::abs(x);
    R x2 = x * x;
    R x3 = x2 * x;
    R y = 0;
    R q = R(5./2.) * x2; // a reoccurring term
    R p1 = R(1) - q + R(3./2.) * x3;
    R p2 = R(2) - R(4) * x + q - R(1./2.) * x3;
    y = (x < R(2)) ? p2 : y;
    y = (x < R(1)) ? p1 : y;
    return y;
}

__m128 Hermite3rdOrder4x(__m128 x)
{
    x = _mm_andnot_ps(_mm_set1_ps(-0.0f), x);
    __m128 x2 = _mm_mul_ps(x, x);
    __m128 x3 = _mm_mul_ps(x2, x);
    __m128 y = _mm_set1_ps(0.0f);
    __m128 q = _mm_mul_ps(_mm_set1_ps(5./2.), x2);
    __m128 p1 = _mm_add_ps(_mm_sub_ps(_mm_set1_ps(1), q), _mm_mul_ps(_mm_set1_ps(3./2.), x3));
    __m128 p2 = _mm_sub_ps(_mm_add_ps(_mm_sub_ps(_mm_set1_ps(2), _mm_mul_ps(_mm_set1_ps(4), x)), q), _mm_mul_ps(_mm_set1_ps(1./2.), x3));
    __m128 m2 = _mm_cmple_ps(x, _mm_set1_ps(2));
    y = _mm_or_ps(_mm_and_ps(m2, p2), _mm_andnot_ps(m2, y));
    __m128 m1 = _mm_cmple_ps(x, _mm_set1_ps(1));
    y = _mm_or_ps(_mm_and_ps(m1, p1), _mm_andnot_ps(m1, y));
    return y;
}
```

**Comment by paulfd** [comment]
This is done in #238.

I still have some cutesie idea in the back of my mind but let's see this later then.
