### ISSUE TITLE
Add pitch_keycenter=sample

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#357]
When this is used, the sample's pitch is taken from the root key set in file metadata.
The `SF_INSTRUMENT` should provide this information.

**Comment by kinwie** [comment]
This is a good opcode that already exist since sfz version 1 and not yet documented at sfzformat.com.
It's a very helpful opcode when use on the right purpose.
I can help provide the explanation and examples to documented it at the page.
However, this opcode also recognized by ARIA but behave differently from the original sfz.
Afaik, almost no existing sfz presets use this opcode so its implementation in sfizz should not taking ARIA's compability into consideration.
I would say, follow original sfz behavior is make more sense for this opcode usage.

**Comment by kinwie** [comment]
This is a good opcode that already exist since sfz version 1 and not yet documented at sfzformat.com.
It's a very helpful opcode when use on the right purpose.
I can help provide the explanation and examples to documented it at the page.
However, this opcode also recognized by ARIA but behave differently from the original sfz.
Afaik, almost no existing sfz presets use this opcode so its implementation in sfizz should not taking ARIA's compability consideration.
I would say, following original sfz behavior is make more sense for this opcode usage.

**Comment by kinwie** [comment]
Tested this. It works fine in the latest build
