### ISSUE TITLE
How to interpret lfoN_phase

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#360]
We have a problem with this opcode because ARIA and Cakewalk interpret the value differently.
Candiate solutions are as follows, with respective advantages and inconvenients.

1. Use Cakewalk range 0-360
- (+) it complies to the SFZ standard as established by RGC
- (+) it uses a consistent unit with the larger set of opcodes (eg. `apan_phase`)
- (-) few existing instruments have it
2. Use ARIA range 0-1
- (+) compatible to many existing instruments, which includes Garritan's
- (-) inconsistent with other opcodes like `apan_phase` which use degrees
3. Hybrid: use ARIA if value within ±1, otherwise Cakewalk
- (+) compatible with both, for most cases
- (-) doesn't work with some cases of modulations
    (eg. I want the phase CC to perform 2 wraps using ARIA semantics `lfo_phase_onCC1=2.0`)
4. Compatibility modes
- (+) user can manually select a compatibility mode, behavior will be applied accordingly
    this indication may also be provided as a `hint_*` opcode
- (+) there might be a possibility to auto-detect whether an input is compliant to ARIA or Cakewalk
- (-) detecting might not work all the time

**Comment by redtide** [comment]
IMO the ideal solution would be to implement both 1 and 2, make 1 as default and if needed set 2 through some player UI option.
I think that a hint_* opcode, like using a 'd' (degrees) suffix, might be useless since the current instruments have none of them, and it might be possible that some people will never use them also because not even aware about this sad issue.

**Comment by AlexMitchellMus** [comment]
I would prefer 2- ARIA rotation unit as default, with wrapping, throughout sfizz.

If there is a possibility to have degrees with "d" or "°" I think it would be useful to allow users to select what unit to use.

However if it is too confusing to allow both to co-exist, then I would say ARIA, as there is no real difference between rotations and degrees, and they are both valid units for expressing phase.

**Comment by redtide** [comment]
I don't see the point to use those suffixes since are not used also on other opcodes using the same unit and AFAIK in general units in sfz are not used at all, so it will only add confusion and inconsistency just to try to handle badly an issue created by a different implementation against the original choice.

**Comment by paulfd** [comment]
Although inconsistent I think 2 wins due to the larger number of libraries. A runtime config might still be nice, activated through some hint_ opcode and/or a UI option.

**Comment by AlexMitchellMus** [comment]
If rotation is chosen, it would be good to use it throughout sfizz instead of degrees?

**Comment by paulfd** [comment]
> If rotation is chosen, it would be good to use it throughout sfizz instead of degrees?

I'm ok with this.
