### ISSUE TITLE
Reset the smoothccs

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#382]
In ARIA, when the playhead is repositioned, the smoothcc states are expected to be reset.

For example if a CC automation is manipulating the pitch
(127, 0, ..., 0)
and the track is played in a loop, the filter will smooth down, but it will not smooth up when the track loops to beginning.

**Comment by paulfd** [comment]
Do you have an example? I tried in Reaper windows today and got this:

https://user-images.githubusercontent.com/15227713/110633439-0b103600-81a9-11eb-86df-6ba9a2984c1a.mp4


SFZ file used:
```sfz
<region> sample=*sine pitch_cc1=1200 pitch_smoothcc1=100 ampeg_release=3
```

**Comment by jpcima** [comment]
That's possibly the one, I'm not currently running Windows to check it
[smooth.zip](https://github.com/sfztools/sfizz/files/6116114/smooth.zip)

**Comment by AlexMitchellMus** [comment]
I have tested in both Reaper & Apple Logic using @paulfd test file.
Looping does not reset smoothers, and there is a noticeable dip when the loop point wraps around the beginning. (cc 127 -> 0)

As looping can be used as a live performance tool, like within a clip launching DAW, it is acceptable, and expected behaviour for sfizz to not clear smoothcc when looping.

However both Reaper and Logic **offline render** Sforzando with smoothcc reset from the beginning of the render: 

## Offline render tests:
### REAPER cc1: 0->127:
![REAPER_top_sfizz_v_bottom_sforzando_smoothcc](https://user-images.githubusercontent.com/12004932/110791274-efe51980-82c1-11eb-9b92-a62e60b217d3.png)
### LOGIC cc1: 0->127:
![LOGIC_top_sfizz_v_bottom_sforzando_smoothcc](https://user-images.githubusercontent.com/12004932/110791365-07240700-82c2-11eb-86e4-dc33d065c8c0.png)
### LOGIC cc1: 127->0:
<img width="1092" alt="Screen Shot 2021-03-11 at 11 51 27 pm" src="https://user-images.githubusercontent.com/12004932/110794147-5a4b8900-82c5-11eb-8bca-3b8ac2b7161b.png">


Difference between Logic & Reaper is due to Reaper not being able to draw a straight cc line between two points (at least I couldn't work it out) This doesn't effect the validity of the test.

**Comment by paulfd** [comment]
I don't understand what you're testing on these. It's offline rendering with the CC in a "nonzero" state?

I guess hosts would probably signal something like all sound off that should reset the CC state, or if the transport is at 0 then all CC state should be reset maybe...

**Comment by AlexMitchellMus** [comment]
> I don't understand what you're testing on these. It's offline rendering with the CC in a "nonzero" state?

Yes. I play the track and wait untill cc moves to 127. (The cc is a ramp 0->127)

Then I stop transport.
I then export offline.

Whatever value the cc was on before render, sfizz will render that into the final output.

Rendering tracks needs to be reproducible, this smoothing issue would stop me from using smoothing with sfizz.

We cant expect users to make sure their cc value is smoothed to around the start value?

It has to be assumed that smoothing is reset when offline starts rendering, or play is initiated. The current value of cc then becomes the most important. As in this example, the accumulated smoothing will be junk data.

Reset on transport play is specifically important- as not all DAW's have offline (freewheel) render. Also- when I press play to hear a song in my DAW, I don't want to hear junk CC's smoothing in any random direction.
