### ISSUE TITLE
Loop ticking on pitched keys

### ISSUE THREAD

**Issue by kinwie** [sfztools/sfizz#395]
In attached example file, the looped sample played fine at its root key. But when pressing other (pitched) keys, the loop is ticking in sfizz
[Loop_ticking_on_pitched_keys.zip](https://github.com/sfztools/sfizz/files/5146335/Loop_ticking_on_pitched_keys.zip)

**Comment by kinwie** [comment]
I think this problem is that, sfizz not reading well the loop end point in the metadata, if the value is maximum (same as the sample's end).
I edit the the wav in the attached example file, move the loop-start and loop-end less 1 point, the ticking is gone.

**Comment by jpcima** [comment]
I believe there's a bigger problem at play here. The loop code suffers of an issue in relation with the block rendering.
Not tried yet, but based on my current understanding.

To explain it shortly, suppose there is a audio loop of size 100 frames.
- If the audio host asks sfizz to serve 200 frames, 
      - block 0-100 will be filled with our loop 0-100 frames
      - block 100-200 will be filled again with our loop 0-100 frames
- Now if the audio host asked to serve 300 frames
      - block 200-300 would be filled **wrongly** with input audio range 100-200
        because code must offset the input index back by 100 **2 times**, but the buggy code does not more that 1

So that's possibly the problem, if you have a buffer size too large, the multiple loops that occur within a single buffer don't offset correctly after the first one.

**Comment by paulfd** [comment]
I think this can be closed now, considering #464

**Comment by kinwie** [comment]
Yes, sorry, just have this checked. The tick is gone. Thanks
