### ISSUE TITLE
add license text to GOVERNANCE.md

### ISSUE THREAD

**Issue by alex-tee** [sfztools/sfizz#409]
I'm interested in reusing this and adapting it, but without a license strictly speaking I can't legally do it.

I suggest adding this at the end:
```
Copyright (C) <year> <name

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.
```

Or even CC0 if you do not want attribution "This file is in the public domain (CC0 1.0 <https://creativecommons.org/publicdomain/zero/1.0/>)"

**Comment by paulfd** [comment]
You mean for the actual governance text?

**Comment by alex-tee** [comment]
yeah

**Comment by alex-tee** [comment]
GNU recommends the all-permissive license above https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html

**Comment by paulfd** [comment]
OK this one is nice, I removed the blurb about the copyright notice because there's in fact no copyright notice in the file. I do not think it's so relevant for such a file. The current message may be held as me allowing explicitely anyone to modify and redistribute all or part of the text with the license but without copyright attribution.

Enjoy ;-)

**Comment by alex-tee** [comment]
perfect, thanks!

**Comment by alex-tee** [comment]
> Copying and distribution of this file, with or without modification, are permitted in any medium without royalty this notice is preserved
>without royalty this notice is preserved

I think it's missing a "provided that", or I guess you could just remove the "this notice is preserved"

**Comment by paulfd** [comment]
Indeed my bad. Fixed.
