### ISSUE TITLE
Multiple <global>

### ISSUE THREAD

**Issue by jpcima** [sfztools/sfizz#423]
The instrument Unreal Standard Guitar is reported as non working. @st3r4g
https://unreal-instruments.wixsite.com/unreal-instruments/standard-guitar

The reason appears to be: the instrument contains multiple `<global>` headers.
These globals have different values for `sw_default`.
Apparently, sfizz should handle `sw_default` independently for each of these globals.
Currently one applies for the entire system.

There might be other problems as well. @st3r4g has provided a patch that permits to get sound out of the instrument.
https://gist.github.com/st3r4g/fa238f72bd49a171933499cd86536289

**Comment by kinwie** [comment]
`sw_default` is working globally per sfz file in ARIA. Last one win.
But defining it multiple times with different values is obviously a wrong thing to do.

**Comment by st3r4g** [comment]
Basically the patch does two things:

1. removes the individual `sw_{lokey,hikey,default}` in each included file and defines them just once in the main `.sfz`
the original settings `sw_lokey=f0 sw_hikey=g#7` and the different `sw_default` values make zero sense to me, although the instrument works in sforzando.
2. turns the multiple `<global>` into `<master>`
this also seems necessary to get a working instrument. How does `sfizz` handle multiple `<global>`?

**Comment by paulfd** [comment]
> Basically the patch does two things:
> 
>     1. removes the individual `sw_{lokey,hikey,default}` in each included file and defines them just once in the main `.sfz`
>        the original settings `sw_lokey=f0 sw_hikey=g#7` and the different `sw_default` values make zero sense to me, although the instrument works in sforzando.

It makes little sense for sure, but it should still work out.  I think the behavior you see comes from the fact that we only consider the last `sw_default` for all regions, regardless if a region appears `sw_default` is set. I would say that it's out of spec to have different `sw_default` but it should not be hard to support if we want to match sforzando's behavior.

>     2. turns the multiple `<global>` into `<master>`
>        this also seems necessary to get a working instrument. How does `sfizz` handle multiple `<global>`?

Well loosely as do most implementations I think :) A new `global` will reset previous ones but other than this it's pretty much like all other hierarchy opcodes. Some opcodes are only parsed within a `global` though.

**Comment by st3r4g** [comment]
After a bit more testing I'm quite sure that the actual problem is the keyswitch range overlapping with actual notes.
I updated the patch, which is just the result of:
```
sed -i 's/sw_hikey=g#7/sw_hikey=a1/' *
sed -i 's/sw_hikey=d7/sw_hikey=a1/' *
```
run from the `Programs/Individual Patchs/Standard_Guitar_KSOP` folder.
That alone produces a working instrument, so I think I've pinpointed the issue.

**Comment by paulfd** [comment]
Okay, then it might just be a bug ;)

**Comment by st3r4g** [comment]
I have a minimal example. This is a working instrument:
```
<global>
sw_lokey=c1
sw_hikey=c3 // sw range doesn't contain note c4
sw_last=c2

sw_default=c2

<region>
sample=Samples/Sus_Down/c4_Sus_Down1.flac
key=c4
```
This is not (no sound, keyswitch doesn't work):
```
<global>
sw_lokey=c1
sw_hikey=c5 // <- now sw range contains note c4
sw_last=c2

sw_default=c2

<region>
sample=Samples/Sus_Down/c4_Sus_Down1.flac
key=c4
```

**Comment by kinwie** [comment]
I just checked those two examples. Actually sfizz behaves just like Cakewalk DropZone, the Keyswitch range is exclusive, which mean it's preserved only for keywitching function. While sforzando made the keyswitch range available as note range also.

In your first example. If you hit note within the keyswitch range, e.g. F1, then your note C4 will not be sounding anymore.
It behaves the same in DropZone too. I'm fine with either :D

**Comment by kinwie** [comment]
Btw, the mentioned sfz instrument file also has similar issue in TX16WX sampler

**Comment by AlexMitchellMus** [comment]
For legato instruments that use `sw_down` they will need Sforzando behaviour to function correctly AFAIK.

**Comment by paulfd** [comment]
OK after looking into this, I know where the "problem" is and I am a bit torn. Let me explain:

`sw_lokey` and `sw_hikey` are used within sfizz along with `sw_last` to determine an *exclusive* set of keyswitches. This means that for regions, the last *potential* keyswitch (any key within `sw_lokey` and `sw_hikey`) will determine if the region is active, *and this is checked before checking if the region triggers a note*. This means that for your minimal example, the c4 region is activated by default, and then deactivates itself when c4 is pressed because it is a potential keyswitch but not one referenced by the `sw_last` opcode.

All in all, this is not entirely unreasonable if you think of exclusive keyswitches, which is why I am a bit torn. It seems that what sforzando is doing is basically taking into account not only the keyswitch range (`sw_lokey` and `sw_hikey`) but also the *actual* existing keyswitches. So you're not exclusive on the range but only on the effective keyswitches as parsed over the sfz file. This creates some complexity on the engine side because I'd need to somehow "resolve" the keyswitches after all regions are loaded, and create some form of keyswitch groups. This also opens the door for weird corner cases. Consider for example the following in sforzando:

```sfz
<global>
sw_lokey=c1 sw_hikey=c2

<region>
lokey=c4
hikey=d4
sw_last=c5
sample=*sine

<global>
sw_lokey=c1 sw_hikey=c5

<region>
lokey=c5
hikey=d5
sw_last=c4
sample=*saw
```
On loading no key will sound. Upon pressing c4, you do not hear a sine, but c5->d5 become playable (active on the gui). Pressing d5 will make a saw sound. Pressing c5 will make no sound, and will activate c4->d4 (active on the gui) while deactivating c5->d5. Pressing d4 *makes no sound*, I guess because the keyswitch range did not include c5 when this region was parsed, but the note appears active on the gui still. Pressing c4 does not make any sound either, but deactivates c4->d4 and activates c5->d5.

I suspect this last part is a bug in Sforzando given the logic it implements, but I think it illustrates the complexity of the problem if you are not "strict enough" on this. I'm not saying wontfix but I'm not sure how to fix it in a sane way (today, maybe when I think about it more it'll be fine :slightly_smiling_face: ). What do you guys think?

**Comment by kinwie** [comment]
I have some opinions but I need to do some more checks first to propose a solid suggestion for this :)

**Comment by st3r4g** [comment]
Imho it depends on how many instruments are relying on this behaviour, which I don't know since I've started using sfz instruments this week. I found that also METAL-GTX (by Unreal Instruments too) suffers from this. The reason for the extended range (which I didn't realise at first) is that not all articulation are in the range `g#0-a1`, there is about an octave of articulations in the upper end too (so my patch is not good).

sfizz's behaviour is what I expected after reading the spec, so I'd rather "fix" the instrument instead. What would be the best way? Use the proper range for each `sw_last` (if it works)? Move all articulations to the low end? Use CC instead of notes?

**Comment by paulfd** [comment]
Well not sure the spec lends itself well to split keyswitch ranges to be honest, which is an argument for the more flexible behavior of sforzando.

> Use the proper range for each sw_last (if it works)? Move all articulations to the low end? Use CC instead of notes?

For sfizz I guess any of these should work. The keyswitch range is not "global", it is set in each region, so you can try.

**Comment by kinwie** [comment]
So I break down the `sw_xxx` opcodes and comparing behaviours.

- The specs didn't made a strict rule for `sw_lokey` and `sw_hikey` and ARIA/sforzando has a loose implementation for it. These two opcodes also cause issue in rgc sfz and DropZone, also in sfizz. Actually if we want to go further for sfizz, these two opcodes can just be deprecated imo (if the keyswitching detection can be possibly taken from `sw_last` opcode only). I have to mention other sampler, Kontakt, that it doesn't need these keyswitch-range to be defined which is much less-confussion. Otherwise, just do like ARIA did :)

- The issue for `sw_down` is that : When there is a sw_lo/hikey present and the sw_down key is out of sw_lo/hikey range, it won't be working. So, maybe deprecate the sw_lo/hikey will be solving this issue also.

@paulfd 
So, my suggestion for this, is making the keyswitch functioning more loosely and flexible like ARIA or much more :)) as the today's growing sample libraries design also more and more sophisticated.

**Comment by st3r4g** [comment]
> The keyswitch range is not "global", it is set in each region, so you can try.

I tried but (assuming I did it right) there's a problem: if I press just the switches in the lower region it works, but as soon as I press a switch in the upper region I get two voices on each note press (seems like the upper keyswitch fails to deactivate the lower one)

**Comment by paulfd** [comment]
Right, it's like 2 keyswitch groups then. Exclusive within the group but not between themselves. Is there an option e.g. in sforzando to have multiple keyswitch groups like this?

@st3r4g For this particular issue I think there is really no choice for us but to implement Sforzando's behavior ;)

**Comment by AlexMitchellMus** [comment]
@paulfd I think its reasonable to take a middle road:

If a SFZ Script has keyswitches inside sw_lokey/sw_hikey, then make those switches exclusive.

However- I'm also coming from a POV of wanting more advanced keyswitch behaviour in sfizz, (and SFZ).

Keyswitches are a fantastic way to add expressive control to an instrument. With advanced libraries using upwards of 40 per instrument. In Kontakt it's also possible to place keyswitches on a different MIDI channel, allowing even greater control.

If being stricter allows more room to grow in the future- without getting tangled up in the meantime, I see no issue with that.

**Comment by paulfd** [comment]
Just to add more information on this issue: keyswitches that are out of `sw_lokey/sw_hikey` in Sforzando appear on the keyboard but do not switch anything.
