### ISSUE TITLE
LV2 on Windows: resource problems for the UI

### ISSUE THREAD

**Issue by paulfd** [sfztools/sfizz#522]
![image](https://user-images.githubusercontent.com/15227713/97028571-9f606000-155c-11eb-8767-aedd9460231a.png)

This is in Mixbus 6.1 and Ardour 6.3.

**Comment by jpcima** [comment]
Custom fonts paths are available only for msvc builds running on Windows 10.
In older Windows and in MinGW, install the fonts in the system directory.
Our installer does this automatically.

**Comment by paulfd** [comment]
Ok so that's because I just copied the LV2 directory without installing. I'll try later.

Oct 23, 2020 19:04:20 JP Cimalando <notifications@github.com>:

**Comment by redtide** [comment]
AFAIK most of our packages have no installer

**Comment by paulfd** [comment]
> Custom fonts paths are available only for msvc builds running on Windows 10.
> In older Windows and in MinGW, install the fonts in the system directory.
> Our installer does this automatically.

However this was with msvc on windows 10 so we may yet have a problem :D

**Comment by jpcima** [comment]
It's available since some particular revision of windows sdk.
Check if this part of code gets compiled in your environment.
https://github.com/sfztools/vstgui/blob/055cbcc9ae858f0b07d5d86c205a1111e2fba7a4/vstgui/lib/platform/win32/direct2d/d2dfont.cpp#L35

**Comment by jpcima** [comment]
The problem is as follows:
- Under Windows, we are using this as a resource path: `<lv2-bundle-path>\Contents\Resources\`
- The LV2 bundle path is provided as an argument to the `instantiate` call
  The LV2 specification has to say: "Path to the LV2 bundle which contains this plugin binary."
- However, what we get is not the bundle path of `sfizz.lv2`, it's the subdirectory which contains the DLL instead.

![Capture du 2020-10-24 05-05-17](https://user-images.githubusercontent.com/17614485/97066515-86849880-15b6-11eb-9ee2-de5aae0bd6d7.png)

It seems like an anomaly of Ardour or Lilv. For now I can implement a workaround to this.
