### ISSUE TITLE
sfizz vs Carla, instrument choice is not saved correctly

### ISSUE THREAD

**Issue by jamshark70** [sfztools/sfizz#596]
Under #595, I was told that sfizz as a plugin would save its settings properly if I save the project on a filesystem that supports symlinks.

However, this is not true for Carla.

1. Create a new Carla project.
2. Add a sfizz plugin.
3. Choose a sampled instrument and verify that audio is produced correctly.
4. Save the Carla project to an ext4 filesystem.
5. Close Carla.
6. Relaunch Carla and open the project file.
7. Open the sfizz instrument. Now it says "DefaultInstrument" instead of the instrument selected earlier.

I might anticipate mutual buck-passing here: sfizz expects the symlinks to be created under Carla, and Carla may well say "why do you need symlinks?"

I had really hoped to find an alternative to Ardour because its MIDI editing interface is unbearable. Waveform11 look(ed) promising but it doesn't support LV2 *or* JACK MIDI. So I thought maybe I could host sfizz LV2 in Carla and pipe MIDI/audio in and out. But... the project fails to restore properly. So after two days, I'm still at step 1.

(I'm rapidly running out of FLOSS options. I'd love to be able to say that I could complete this project with FLOSS but this is looking increasingly unlikely.)

**Comment by jpcima** [comment]
Hi @jamshark70 
There was a report of problems with restoring LV2 files by their path. Right now the problem is not well identified unfortunately.
In LV2, sfizz is calling host's mechanisms to save and restore paths portably, but there appear to be trouble in some circumstances.

You may instead use the VST3 version. In the later versions of Carla and Ardour, VST3 support is available and sfizz is compatible.
It uses a file loader of SFZ which is more robustly implemented using fuzzy search, which looks at user's SFZ files like a collection, and is able to load when the project is shared across machines.

**Comment by jamshark70** [comment]
Ok, I just wanted to be sure the issue is reported. Hope it can be fixed at some point.

I'm now using Reaper for this project (which, come to think of it, is probably loading the VST3 version of sfizz by default, and accordingly having no trouble with restoring the session). Though not free/libre, it works.

**Comment by falkTX** [comment]
This is working correctly with latest sfizz develop branch and carla since https://github.com/falkTX/Carla/commit/5f3741c5d81672c4c65c7f02e499078e90e7a64c

**Comment by paulfd** [comment]
Thanks @falkTX  !
