### ISSUE TITLE
Pressing 'Load File' doesn't do anything

### ISSUE THREAD

**Issue by heretoenhance** [sfztools/sfizz#637]
I installed sfizz from Arch official repos.
When I open Sfizz in Carla or Ardour and press on 'Load file' from the context menu, it doesn't let me choose a .sfz file, it doesn't do anything.
'Edit file' works. 
Even pressing on the Scala file doesn't let me choose a file.

**Comment by jpcima** [comment]
Hi @heretoenhance. It needs the `zenity` package installed.

It is not listed in the deps array of the package `sfizz` from `community`.
And it appears `surge` is in the same case. Let's ask @dvzrv.

**Comment by heretoenhance** [comment]
Thank you for your immediate reply. It works after installing zenity.

Should I close the issue or wait for @dvzrv to see this?

**Comment by jpcima** [comment]
Keep it open, as a remainder that we need to document this somewhere.
The question comes up quite often.

**Comment by dvzrv** [comment]
@jpcima would that be an optional runtime dependency? I can certainly add that to the PKGBUILD.

**Comment by jpcima** [comment]
@dvzrv thanks, is it a problem to list it as mandatory dependency instead?
it's a rather major feature that depends on it.
I've also thought previously about linking tcl/tk, which could provide us a fallback dialog.

**Comment by falkTX** [comment]
This could be integrated with the lv2ui requestValue, right? So it triggers a host-generated file dialog, instead of one via plugin.
See http://lv2plug.in/ns/extensions/ui#requestValue
(This is supported by Qtractor, Carla, Ardour, jalv and maybe even others)

VST2 had something like that too, but not all hosts cared to implement it.
Not sure about VST3.

**Comment by jpcima** [comment]
>This could be integrated with the lv2ui requestValue, right? So it triggers a host-generated file dialog, instead of one via plugin.

By LV2's file request interface, is it possible to configure more in depth the file dialog that we obtain? in particular, the file filter, and open/save mode.

**Comment by falkTX** [comment]
> > This could be integrated with the lv2ui requestValue, right? So it triggers a host-generated file dialog, instead of one via plugin.
> 
> By LV2's file request interface, is it possible to configure more in depth the file dialog that we obtain? in particular, the file filter, and open/save mode.

No, and I find it a real problem too.

We have to propose something to the lv2 specs. Maybe mimetype..?

For MOD, we went with a custom way of handling things, since the file manager has only very specific files that it allows the user to upload. So a plugin UI request can be made to be more exact.
See https://moddevices.github.io/mod-sdk/mod/#fileTypes

**Comment by jpcima** [comment]
> We have to propose something to the lv2 specs. Maybe mimetype..?

We don't have sfz registered is a mimetype yet, neither at IANA not XDG as `x-` mimetype, so it's a problem. We know that Polyphone registers it as custom type for their own need.

The wish list for file dialog, from about what I recall
- save/open mode
- multiple file filters (accepts both SFZ and sound files)
- auto-append file suffix

There's also the "ask to overwrite" feature, which I kinda give up on, because I find it badly implemented together with "auto-append" feature, which can work misleadingly in ambiguous cases.

**Comment by jpcima** [comment]
The editor will now display an informative message and block, in the case that zenity is absent on the system.
