### ISSUE TITLE
Please add cmake variable to use external packages instead of bundled dependencies

### ISSUE THREAD

**Issue by yurivict** [sfztools/sfizz#647]
For example ```abseil-cpp``` bundled here https://github.com/sfztools/sfizz/blob/develop/CMakeLists.txt#L50 exists as a package in all distributions: https://repology.org/project/abseil-cpp/versions

Bundling isn't a sustainable practice because if all packages would bundle all of their dependencies there would be an exponential explosion of both CPU time needed to rebuild them and of space needed to install them.

**Comment by jpcima** [comment]
Hello, it's a fair remark but mainstream distributions of free OS are not shipping Abseil in their default repositories.

**Comment by jpcima** [comment]
But providing it as option, yes I understand what you mean.
This should be feasible,

**Comment by yurivict** [comment]
Same for sfztools:simde - it is also available, but not as widely: https://repology.org/project/simde/versions

**Comment by jpcima** [comment]
We have a degradation of performance and a bug on upstream SIMDE.
This can happen when upstream merges the fix and publishes.

**Comment by jpcima** [comment]
It is fixed by PR #648 and #649, which add the options `SFIZZ_USE_SYSTEM_ABSEIL` and `SFIZZ_USE_SYSTEM_SIMDE` respectively.

- When it detects a bad version of SIMDE (which currently is all of them), a warning message shows.

- Abseil can produce link errors if not careful. When Abseil is built for c++ `17` compatibility, the replacement `string_view` is not built. Building sfizz, which defaults to `11`, `string_view` implementation will not be available in static libraries.
In this case, sfizz must be build with `-DCMAKE_CXX_STANDARD=17` flag. It's regrettable that abseil does not propagate the cxx standard property to the dependents.
