### ISSUE TITLE
Offline option for highest quality

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfztools/sfizz#895]
Currently sfizz gives users the option to set quality for on-line rendering, and uses the highest quality for offline.

It would be clearer, and also allow a useful feature, to have a toggle button in the settings to use the selected online quality, or highest:

[✓] highest quality offline render

This is because there could be a difference between the selected rendering method, one which a musician may intentionally want, or become accustomed to.

**Comment by paulfd** [comment]
I'd say an option to set the quality level of the offline rendering is even better no?

**Comment by alcomposer** [comment]
Possibly not. Here is my logic:

1) If we have option to set offline qualtiy value, then we add more drop-downs to settings, and confusion.
2) I only can think of one reason why someone would want to not render in highest quality, and that is because they like the sound the are already hearing live.
3) This suggestion would only add one toggle to settings UI
4) The name of the button is self explanatory, and gives meaning to the rest of the quality settings.
5) Unlike Video / 3D rendering, Audio processing is many orders of magnitude faster. While 3D software allow advanced settings between viewports, and final render, we don't need to worry about quality from a performance perspective.

**Comment by AlexMitchellMus** [comment]
Possibly yes. 

I was only thinking about simplifying the implementation. But I realise now that the user may have a personal taste for rendering (given the extensive preferences).

Hence it may be easier to implement both than to worry about it now or in the future.
