### ISSUE TITLE
Mod Duo choke groups dont work (8.0-0)

### ISSUE THREAD

**Issue by LeiaHedberg** [sfztools/sfizz#971]
Hello, Im running 8.0-0 on my Mod Duo X (not sure if this applies to other versions of sfizz, only use it on my Mod Duo X) and it is completely ignoring choke groups.

**Comment by falkTX** [comment]
You mean MOD Duo X in the title.
The build is using a1cef9ba16c2c6603e1c7611932b61a701cc7647 which is fairly recent.

**Comment by paulfd** [comment]
Do you have a non-working SFZ file that illustrates the issue? (If only because there are slightly different ways to create "choke" groups in SFZ)

**Comment by LeiaHedberg** [comment]
Heres a simple patch that doesnt work: https://drive.google.com/file/d/1fv-IdFmZ0sgTawiOs7pzIsQ1UfqcUXxU/view?usp=sharing
The choke group type that doesnt work is group=(x) off_by=(x)

**Comment by praashie** [comment]
This is the `Sunday Night Sequenced Thing Bugged.sfz` in question:

```
<group>

<global>ampeg_release=300

<region> sample=SFZ 1-Sunday Night Sequenced thing.wav key=11 group=1 off_by=1
<region> sample=SFZ 2-Sunday Night Sequenced thing.wav key=21 group=1 off_by=1
<region> sample=SFZ 3-Sunday Night Sequenced thing.wav key=12 group=1 off_by=1
<region> sample=SFZ 4-Sunday Night Sequenced thing.wav key=22 group=1 off_by=1
<region> sample=SFZ 5-Sunday Night Sequenced thing.wav key=13 group=1 off_by=1
<region> sample=SFZ 6-Sunday Night Sequenced thing.wav key=23 group=1 off_by=1
<region> sample=SFZ 7-Sunday Night Sequenced thing.wav key=14 group=1 off_by=1
<region> sample=SFZ 8-Sunday Night Sequenced thing.wav key=24 group=1 off_by=1
<region> sample=SFZ 9-Sunday Night Sequencedn thing.wav key=15 group=1 off_by=1
```

There is indeed buggy behavior:
- When a note is held down while another one is triggered, `off_by` muting works correctly
  - Using `off_mode=normal` with `ampeg_release=1` confirms that the default setting is `off_mode=fast` 
- When a note is released quickly (staccato) before playing another one, `off_by` muting **does not work**
  - This conflicts with what `off_mode=fast` is supposed to do.

This might be the location of the issue: https://github.com/sfztools/sfizz/blob/15370fa4391d89c2fd178f0e3b82a56ffc1e5800/src/sfizz/Voice.cpp#L1662-L1681

When a region is in its release stage, `Voice::checkOffGroup` completely ignores `off_by`.

In the case of this instrument, the problem is fixed when `ampeg_release=300` is replaced with `loop_mode=one_shot`.
Another workaround is `note_polyphony=1`

**Comment by paulfd** [comment]
Thanks both, I'll try to patch it and see if it doesn't break the existing polyphony tests; could take a couple days since I'm quite busy atm. There's now a boolean that can be checked to differentiate between a note that is just releasing and one that was "offed", so I'll use this.

For this particular case though I do think `loop_mode=one_shot` is more idiomatic.

**Comment by praashie** [comment]
I wrote a one-liner patch that passes the test cases, and I also wrote a new test case for staccato off groups that fails without the fix. PR incoming.
